### ISSUE TITLE
beautiful app.  couple of ideas

### ISSUE THREAD

**Issue by jawz101** [TylerWilliamson/QuickWeather#1]
Widgets and F-Droid.  This really is too nice to not get some love on F-Droid.

And every weather app needs widgets.  You are good with design so I bet they'd look great.

**Comment by maityamit** [comment]
What I will provide ?
Please say

**Comment by TylerWilliamson** [comment]
Thank you for the suggestions @jawz101. I was planning on adding QuickWeather to F-Droid eventually, but added it in the latest release (1.3.1). You can view QuickWeather on F-Droid [here](https://f-droid.org/en/packages/com.ominous.quickweather/).

Unfortunately, at this time I do not have any plans to create widgets

**Comment by haarp** [comment]
Another vote for widgets here. QuickWeather is beautifully simple, and I'd love to use it as the sole weather app on my system :)
