### ISSUE TITLE
App dont work on Android Business profile 

### ISSUE THREAD

**Issue by grossfriedrich** [TylerWilliamson/QuickWeather#100]
Hi, this app don't work on a Android Business profile. 
The app starts, i could not compleet the First Steps pages. I stuck in a loop.
On the personal profile it works fine.
I want to use it in my business profile, because i use Shelter to contol all my apps.
It would be great if you can fix this.

**Comment by TylerWilliamson** [comment]
When you get "stuck in the loop", are the settings that you have chosen still set? Are there any that are not set? For example, are there no locations?

**Comment by marcdw1289** [comment]
I am not using any profiles but I also got stuck in a loop. After pressing FINISH it just loops around.
Discovered that I had to enable Current Weather notification for the app to work. I had enabled only alert notifications initially.

I know this issue is old but figure it's a maybe thing.

**Comment by TylerWilliamson** [comment]
I finally got a chance to test this, but could not replicate the issue. I created a work profile on a virtual device running Android 14, installed QuickWeather to that profile, and it went through setup correctly. This issue may have been resolved with the other initialization bugfixes I have recently deployed. I will be closing this ticket, but if you are still experiencing the issue, please give as much information as possible and I will reopen and attempt to fix it.
