### ISSUE TITLE
Current weather notification is half covered

### ISSUE THREAD

**Issue by dleer** [TylerWilliamson/QuickWeather#104]
![Screenshot_20231024-104936-354](https://github.com/TylerWilliamson/QuickWeather/assets/12356696/aa684f63-8523-4a29-97c5-e0edd16cc39d)

It looks this way in both tray and on lockscreen. I tried tweaking Android notification settings but nothing affects it. This is Android 11.

**Comment by dleer** [comment]
> This is a known bug and I have put forth a few attempts to squash this bug, but no luck so far. I'll leave the issue up to track the work. What device are you using?

Ah I see. Thanks for the reply.  I am using a Motorola One Ace 5G.

**Comment by amarradi** [comment]
Today i see the notification is half covered

![Screenshot_20240506-101309.png](https://github.com/TylerWilliamson/QuickWeather/assets/720573/93d76eac-818f-46d8-aba6-5bf7487436cd)

**Comment by TylerWilliamson** [comment]
I may have at least partially resolved this issue in [2.6.11](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.11). I will leave this issue open. Please let me know if you or anyone experiences this issue again

**Comment by TylerWilliamson** [comment]
I have decided to close this issue, with the assumption that the change I made in 2.6.11 should resolve the issue. If anyone encounters this issue again, please leave a comment, preferably with a screenshot, and I will investigate

**Comment by TylerWilliamson** [comment]
@JohnRThomas Can you check the "Current Weather" notification category and confirm if "minimize notifications" is enabled? If not, was this a setting that you changed, or when you installed the app did it do this by default?

**Comment by JohnRThomas** [comment]
You were right! That was it! I don't recall changing that setting, but I may have fat fingered it.

Thank you!

**Comment by TylerWilliamson** [comment]
Great to hear that fixed it. I will need to do some testing to make sure that is the default in newer versions of Android as it was in the past.
