### ISSUE TITLE
Add a check for internet connection before fetching weather data

### ISSUE THREAD

**Issue by Davilarek** [TylerWilliamson/QuickWeather#105]
When I don't use my device, I turn off mobile data/wifi, which sometimes causes the app to fail fetching weather data with error
![IMG_20231028_143951.jpg](https://github.com/TylerWilliamson/QuickWeather/assets/62715937/cf9b9ff4-8aad-4c82-bb48-bbfb4018dfc9)
Would be great if the app would first check for internet connection

**Comment by TylerWilliamson** [comment]
Duplicate #95 - This is intended behavior. Repeating my recommendations from that thread:

> If you would rather not have that error message occur, you can either:
> 
> 1. Disable the "Weather Errors" notification category
> 1. Disable "Weather Alerts", "Current Weather", and "Gadgetbridge" features in QuickWeather settings each night that you turn off data

**Comment by spaetz** [comment]
Hi, just wanted to pile in. I see that error popping up in the notifications every time my screen is off for some time. The difference being that I never turn off my mobile data and Quickweather has all the unlimited mobile data background permissions.

I wonder what could be preventing QW to acess the net.
