### ISSUE TITLE
Bug - mapbox playback speed increases

### ISSUE THREAD

**Issue by sslater11** [TylerWilliamson/QuickWeather#106]
Firstly, well done, this is the first open source app that I can just use without any login details needed. Awesome stuff!

Bug: I can make the map increase it's playback speed via a bug.
1. Tap the play button for the Mapbox
2. then tap one of the weather days that are underneath the map.
3. press back button
4. press play on the map again and it will run faster
5. repeat 5 times for super speedy map
![mapbox-speed](https://github.com/TylerWilliamson/QuickWeather/assets/43177940/19b8e306-1298-4d43-be20-5468bf239d91)

**Comment by sslater11** [comment]
Submitted a small PR to fix this :).
Please accept the PR and close.
Thank you :smile:

**Comment by TylerWilliamson** [comment]
Good catch and good code! Thank you for resolving this bug. Fix merged and included in [2.5.6](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.5.6)
