### ISSUE TITLE
Version issues

### ISSUE THREAD

**Issue by exstntlmsnthrp** [TylerWilliamson/QuickWeather#111]
Hello. First, thanks for a brilliant weather app. I use it daily!

A quick note. There is a version conflict with the newest APK. The release starts it's 2.5.7, whereas both the APK and app version number both say 2.5.6. 

Which is correct?

Thanks.

**Comment by TylerWilliamson** [comment]
Oops, I accidentally uploaded the incorrect version APK. I've updated the [2.5.7 release](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.5.7) with the correct APK. Thank you for catching my mistake!
