### ISSUE TITLE
crosshair/dot for radar

### ISSUE THREAD

**Issue by radicalrusty** [TylerWilliamson/QuickWeather#112]
Hi, I'd like to suggest adding some kind of locator/icon to the screen when viewing the radar so that you can see your precise location on the map. I know that the map is centered, but I think it would also help to have a visual as well. I think a small dot would probably work best for this.

Thank you!

**Comment by TylerWilliamson** [comment]
Duplicate #40 - I will not be adding an indicator to the map. Users can re-center the map if needed using the controls
