### ISSUE TITLE
Wind animations for radar

### ISSUE THREAD

**Issue by radicalrusty** [TylerWilliamson/QuickWeather#114]
I don't know if this is something that is planned or already thought of, but I would really enjoy seeing an (active) visual representation for wind movement when viewing the radar as well. (There's another app that I'm very used to using which has this kind of feature and it's so beautifully done that it makes me just want to look at it for a long time and watch what's happening)

**Comment by TylerWilliamson** [comment]
QuickWeather uses [RainViewer](https://www.rainviewer.com) for its radar images. RainViewer does not have a "wind map", so I cannot implement this request
