### ISSUE TITLE
Wind speed and direction card

### ISSUE THREAD

**Issue by radicalrusty** [TylerWilliamson/QuickWeather#115]
It would be very useful as well to have a card that will show wind speed and direction with a visual indicator (arrows). Graph syle

**Comment by TylerWilliamson** [comment]
Current wind information is already available in the expanded "Main" card of the Current and Forecast Activities. I assume by "graph style" you are looking for a "wind over time" graph similar to the temperature and precipitation graph. I will not be adding a "wind over time" indicator as that will invariable snowball into "everything over time" such as humidity, pressure, cloud cover, etc.
