### ISSUE TITLE
color legend for radar

### ISSUE THREAD

**Issue by radicalrusty** [TylerWilliamson/QuickWeather#116]
I would like the ability to know what colors (specifically for rain) represent when viewing the radar. I love the look of the colors, but what I am wondering is if they correlate to amount of rain/percentage or what exactly they represent? There's not any way for me to tell as it is.

**Comment by TylerWilliamson** [comment]
![image](https://github.com/TylerWilliamson/QuickWeather/assets/8985022/a4314d65-4038-4f5a-add5-c50376d5ef0b)

This is what the colors mean, per [RainViewer](https://www.rainviewer.com/weather-radar-map-live.html). I may add a legend, but frankly, there is not much quantitative data exposed for what each "level" of rain means

**Comment by GuillaumeLeGoc** [comment]
Hi, I was also wondering for the color-code. I don't get the same colors in your link. In your screenshot and in the app, snow and rain colors are overlapping, while on the website I have green in place of the blue tones for rain.
![Capture](https://github.com/TylerWilliamson/QuickWeather/assets/22011231/bf9d5e00-68ac-4e4b-8778-ebb491e2a803)

**Comment by TylerWilliamson** [comment]
Added in [2.6.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.0)
