### ISSUE TITLE
Pressing on day should provide more info

### ISSUE THREAD

**Issue by Donkey-Doug** [TylerWilliamson/QuickWeather#12]
Pressing on the forecast of a specific day should open more information. I think it would be smart to show a graph of that day.

**Comment by TylerWilliamson** [comment]
A forecast activity like you have suggested is planned for a future release. It will likely include a graph of that day's weather.

**Comment by TylerWilliamson** [comment]
[Version 2.0.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.0.0) has been released and this feature has been added
