### ISSUE TITLE
[Feature]Option to disable non-weather alerts

### ISSUE THREAD

**Issue by MartialM1nd** [TylerWilliamson/QuickWeather#121]
Would love an option to disable non-weather related alerts while keeping weather alerts. 
Specifically Amber alerts as I have them disabled at the device level.

**Comment by TylerWilliamson** [comment]
Interesting. I was not aware of this, but it appears that in the United States (and potentially other countries), the various emergency alert systems, including both weather alerts and amber alerts, are combined into one system. These amber alerts should be filtered by OpenWeatherMap, but apparently it slipped through. I'm not sure if I can filter them out completely, but I will add some code to do so. Could you provide any additional information about the alert? For example a screenshot, or the title of the alert? I assume it included "Amber Alert" in it?

**Comment by MartialM1nd** [comment]
Thanks for the quick response. 

I did not take any screenshots unfortunately. I will if another pops up. 
The alerts in question definitely identified themselves as Amber alerts. 

I'd say I have been getting them for maybe 6 months?
