### ISSUE TITLE
No cards in 2.6.1

### ISSUE THREAD

**Issue by taraletti** [TylerWilliamson/QuickWeather#124]
Hi! Hope you're ok. I'm a user of QuickWeather from time now, and updated to 2.6.1 and I've no cards at all. Made a clean install from github (I was updating from f droid). When I touch on set layout I've nothing

**Comment by taraletti** [comment]
![Screenshot_20240112-085526](https://github.com/TylerWilliamson/QuickWeather/assets/60153097/f7279a91-04b6-4a73-b9c1-42f5570db8f8)
Here an example

**Comment by taraletti** [comment]
![Screenshot_20240112-085631](https://github.com/TylerWilliamson/QuickWeather/assets/60153097/0c062892-23e7-42e9-8771-a881acb53016)
Set layout

**Comment by TylerWilliamson** [comment]
This is very odd and it would seem that the internal database did not populate like it should have. I'll work on a fix that should ensure the cards are always there.

In the meantime you may be able to fix this by clearing the app data and reinstalling

**Comment by TylerWilliamson** [comment]
I have released version [2.6.2](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.2) which should fix this issue. Please test it and let me know if you encounter any issues

**Comment by taraletti** [comment]
Now it's ok

**Comment by FaFre** [comment]
@TylerWilliamson please update f-droid, thanks!

**Comment by TylerWilliamson** [comment]
I have no control over F-Droid. They will update the app when they update the app. Please keep comments related to the reported issue

**Comment by FaFre** [comment]
Just informing you that the app in the current release on f-droid includes this bug which makes the app basically unusable, which you might want to be aware of. 

Since it was linked in your README I assumed f-droid an official source for the app.

You can find a guide here on how to maintain your apps on f-droid: https://f-droid.org/docs/How_to_update_an_app/

Switching to the google app store now and give this thing a try.

Wish you a great day!

**Comment by TylerWilliamson** [comment]
F-Droid is an official source of this app, but, as I previously stated, they control the update cadence. If you wish to use the latest version of this app through F-Droid, I would recommend that you read the article that you linked, as it is a guide for users to create a local F-Droid repository and compile the latest version of apps like QuickWeather themselves. Alternatively, please wait a few days and the F-Droid team will update their repository.

Also, as you have noticed, there are indeed other repositories with the latest version of the app available today, such as Google Play Store, or on this very GitHub.
