### ISSUE TITLE
why no Beaufort wind speed 🤷

### ISSUE THREAD

**Issue by dnbttr** [TylerWilliamson/QuickWeather#127]
please consider,thank you

**Comment by TylerWilliamson** [comment]
I'll look into it. Seems like a useful scale

**Comment by TylerWilliamson** [comment]
Added in [2.6.10](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.10)

**Comment by dnbttr** [comment]
thank you!!!
