### ISSUE TITLE
International Dateline Bug

### ISSUE THREAD

**Issue by Albert44de** [TylerWilliamson/QuickWeather#128]
When I reference a location's weather on the other side of the International Dateline, the weekday referenced is incorrect. See the attached.
![Screenshot_20240207-141435](https://github.com/TylerWilliamson/QuickWeather/assets/159330857/1b99dd2e-5119-4701-8c1b-5267161584ec)
![Screenshot_20240207-141408](https://github.com/TylerWilliamson/QuickWeather/assets/159330857/4e32c4c3-d28e-4eaa-8494-76789d642f35)

**Comment by Albert44de** [comment]
Thank you.

**Comment by Albert44de** [comment]
Sorry I didn't realize that my thanks would close the bug.

**Comment by TylerWilliamson** [comment]
Fixed in [2.6.4](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.4)

**Comment by Albert44de** [comment]
Thanks. Since I download from F-Droid, it may take up to a week before I can access the new version.

On March 4, 2024, at 10:49, Tyler Williamson ***@***.***> wrote:

Closed #128 as completed.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/TylerWilliamson/QuickWeather/issues/128#event-12001161171">https://github.com/TylerWilliamson/QuickWeather/issues/128#event-12001161171</a>", "url": "<a href="https://github.com/TylerWilliamson/QuickWeather/issues/128#event-12001161171">https://github.com/TylerWilliamson/QuickWeather/issues/128#event-12001161171</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]
