### ISSUE TITLE
Header for daily data

### ISSUE THREAD

**Issue by Donkey-Doug** [TylerWilliamson/QuickWeather#13]
Perhaps show a header with min and max above this view:

![Screenshot_20210725-031923_QuickWeather_1](https://user-images.githubusercontent.com/50382414/126884708-2342bed0-12e3-4392-b8cc-7a7897e26da7.png)

The estimate should also be added.

Also, make it possible to show the min and max in the graph as well.

**Comment by TylerWilliamson** [comment]
Thank you for the suggestion, but the min and max temperatures can be quickly obtained in that view by scanning the values. Additionally the color coding should assist you in quickly finding the values. The min and max for the graph are on the left side of the graph. Adding an additional header would be redundant and I will not be implementing this request
