### ISSUE TITLE
UV index not available in Gadgetbridge

### ISSUE THREAD

**Issue by DanPT0** [TylerWilliamson/QuickWeather#130]
I use a Amazfit GTS2 watch with Gadgetbridge. The weather information comes from Quickweather. All works fine, only the UV index not. I am not sure where the problem is, is the UV index supported at all, is it a problem of Quickweather or is it a problem of Gadgetbridge. Maybe someone can help. Thanks.

**Comment by TylerWilliamson** [comment]
I just double-checked and QuickWeather should be sending the weather data to Gadgetbridge. I would recommend creating an issue on [the Gadgetbridge issue tracker](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues). Please let me know once they determine it is or isn't a QuickWeather issue.

**Comment by TylerWilliamson** [comment]
Judging by the thread on the Gadgetbridge repo, this bug seems to not be caused by QuickWeather. Feel free to re-open if it is determined that I need to make any changes to QuickWeather
