### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by drveni** [TylerWilliamson/QuickWeather#131]
So far so good.. I ran into the application. Works great so far. The only thing missing is the widget. In 4-5 days ahead, some minimalistic. Or 1 day forecast.Well, I hope it will be in the future  version.

**Comment by TylerWilliamson** [comment]
Duplicate #1 - I will not be adding widgets at this time

**Comment by joho500** [comment]
Hello @TylerWilliamson,
I came across your app which looks very nice. Are you still on the same position on adding widgets? I think this functionality would be appreciated by a lot of people.
Best regards,
Joist
