### ISSUE TITLE
Complaints and feedback.

### ISSUE THREAD

**Issue by NastyFlytrap** [TylerWilliamson/QuickWeather#132]
1: widget please! I dont like the notifications
2: Let us send the notification to oblivion even if we have them on
3: Keep the last weather report until you can refresh it though the internet. Right now if i get a report and i turn my internet off and kill the app it forgets it.
4: You may already be doing this, i dont know, but please make it so it auto updates itself every hour or half our, or something
And finally, 5: Proper options and settings please! The current options button sends me back to the setup page and those are not options really. I want to be able to change how often it updates itself and turn on the auto update function if its not already, turn off unbanishable notifications, that kinda thing.

I would also like a pure black because i have an OLED display. Why waste energy on a 99% black background when it could be 100% black?

**Comment by TylerWilliamson** [comment]
1. Duplicate #1 - I will not be making widgets
2. I do not understand what "send notification to oblivion" means. If dismiss the notification, it will just come back every 15 mins. If that is the request, I will not be inplementing it
3. Duplicate #29 - I am working on "cached mode"
4. What does "auto update" refer to? Automatically updating the app itself? I will not be inplementing that
5. Update frequency is coming in a later release. 

Duplicate #11 - you can support that feature in its already-created thread. Note, the power difference between black and dark grey is negligible on OLED.

Please use the search feature and please keep your feedback to a single topic per issue opened.

**Comment by NastyFlytrap** [comment]
> 1. Duplicate [beautiful app.  couple of ideas #1](https://github.com/TylerWilliamson/QuickWeather/issues/1) - I will not be making widgets
> 
>     2. I do not understand what "send notification to oblivion" means. If dismiss the notification, it will just come back every 15 mins. If that is the request, I will not be inplementing it
> 
>     3. Duplicate [Cache weather data #29](https://github.com/TylerWilliamson/QuickWeather/issues/29) - I am working on "cached mode"
> 
>     4. What does "auto update" refer to? Automatically updating the app itself? I will not be inplementing that
> 
>     5. Update frequency is coming in a later release.
> 
> 
> Duplicate #11 - you can support that feature in its already-created thread. Note, the power difference between black and dark grey is negligible on OLED.
> 
> Please use the search feature and please keep your feedback to a single topic per issue opened.

1: Why?
2: Dismiss, yes. Again, why?
4: automatically update the weather report to a newer one

**Comment by TylerWilliamson** [comment]
1: Widgets are highly subjective. If I open that can of worms, every user will want something different. I also have more pressing items that I am working on, if I get through those, I may come back to widgets. There are plenty of other weather apps with widgets if that is a need for your use case
2: The notification is designed as a persistent notification and would be more annoying for it to keep coming back if you could dismiss it. You may want to set its notification category as "minimized"
4: If you are refering to the notification, it updates every 15mins. If you are refering to within the app, it refreshes when you a) pull down to refresh, b) open or switch to the app, turn off and on the screen, etc. I will not be implementing any other automatic updates
