### ISSUE TITLE
[Feature Request] watch/warning outlines on radar

### ISSUE THREAD

**Issue by shortwavesurfer2009** [TylerWilliamson/QuickWeather#133]
Here in the US The NWS issues watch/warning areas anf they appear on radar. If possible it would be nice to hsve these. One twist that would be useful would be disabling the normal radar view in favor of watch.warning areas only since it can be hard to see yellow watch boxes, etc on a green, yellow, and red storm. I imagine a toggle switch to flip between standard radar and watch/warning outlines only.

**Comment by TylerWilliamson** [comment]
I wish I could implement that, but QuickWeather uses OpenWeatherMap for its Alerts and the [OpenWeatherMap alerts](https://openweathermap.org/api/one-call-3) do not surface that information
