### ISSUE TITLE
queries in plane mode

### ISSUE THREAD

**Issue by Tuxicoman2** [TylerWilliamson/QuickWeather#135]
Hi,

I'm using this software as weather provider for gadgetbridge.

I observed that during plane mode I got notifications about quickweather not being able to resolve 'api.open-meteo.com'.

My expectation would be that it plane mode it doesn't even try 😎

**Comment by TylerWilliamson** [comment]
Duplicate #95 - This is intended behavior. See recommendations in that thread for how to avoid the error message
