### ISSUE TITLE
Translating weather alerts

### ISSUE THREAD

**Issue by MisterCosta96** [TylerWilliamson/QuickWeather#136]
I've noticed the weather alerts/warnings are not translated (Portugal in my case). I had a look at Weblate and couldn't find strings to translate related to this. I assume it is not possible to translate these alerts as it depends on how you obtain information from each country's alerts?

**Comment by TylerWilliamson** [comment]
I just came across [LibreTranslate](https://libretranslate.com/), which is a free, open source  and self-hostable translation service. I will add support for using it to translate weather alerts in a future release

**Comment by TylerWilliamson** [comment]
Added in [2.7.3](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.7.3)
