### ISSUE TITLE
Colored top bar

### ISSUE THREAD

**Issue by Donkey-Doug** [TylerWilliamson/QuickWeather#14]
The green color on the top bar looks out of place. Use same color as the rest of the app (grey or white)

**Comment by TylerWilliamson** [comment]
Could you please describe what "green bar" you see? Preferably with a screenshot.

**Comment by Donkey-Doug** [comment]
My bad, it is not always green.

I meant the colored header bar. It is yellow in the picture below:
![Screenshot_20210725-112030_QuickWeather](https://user-images.githubusercontent.com/50382414/126894184-4610447d-f4fe-403c-ab7d-063a7e574cd7.png)

Material design nowadays requires the same color for the header. For example:
![Screenshot_20210725-112145_Infinity](https://user-images.githubusercontent.com/50382414/126894218-8d06bf92-4cb5-4cb8-a899-4bb7679da9b6.png)

**Comment by TylerWilliamson** [comment]
While I understand the desire for the Toolbar and Statusbar to be neutrally colored, the dynamic color of these elements is a core design principal of QuickWeather and as such, I will not be implementing this feature.
