### ISSUE TITLE
Weather forecast for "today" should update

### ISSUE THREAD

**Issue by yaomtc** [TylerWilliamson/QuickWeather#143]
The day started in the early morning with 100% heavy rain. Afterwards, the rain stopped and was at 0%. However it still says "heavy intensity rain" for today despite it being done for 6+ hours.
![Screenshot_20240330-171255_1](https://github.com/TylerWilliamson/QuickWeather/assets/5534045/0b98db71-9a74-47cd-ba1d-64dc15fad811)
![Screenshot_20240330-170930](https://github.com/TylerWilliamson/QuickWeather/assets/5534045/f9cd6e1f-e6ea-4604-af34-9f10ebb31204)
![Screenshot_20240330-171114](https://github.com/TylerWilliamson/QuickWeather/assets/5534045/2858d0dd-8a13-4aff-8bc3-9fd3ec9890d5)

**Comment by yaomtc** [comment]
I'm using OpenWeatherMap. Is this an upstream issue?

**Comment by TylerWilliamson** [comment]
Neither OpenWeatherMap nor Open-Meteo update the daily forecast for the current day like you are asking. I do not plan to support this feature either

**Comment by yaomtc** [comment]
OK, thanks for the reply anyway, I enjoy your app 👍
