### ISSUE TITLE
Legacy Android Support for Open-Meteo

### ISSUE THREAD

**Issue by TylerWilliamson** [TylerWilliamson/QuickWeather#151]
_Originally posted by @stavpup in https://github.com/TylerWilliamson/QuickWeather/issues/144#issuecomment-2045201688_
![IMG_20240409_163657_1](https://github.com/TylerWilliamson/QuickWeather/assets/10577035/9c30d4da-2d06-4c0d-a77f-7f43c3ead9ba)

Let's Encrypt, the Certificate Authority for Open-Meteo, recently dropped support for Android versions before 7.1.1. This means all calls to Open-Meteo will fail, like the above example.

I am working on a solution

**Comment by TylerWilliamson** [comment]
I have fixed this in [2.6.9](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.9)

**Comment by stavpup** [comment]
Confirmed. Excellent 💯
