### ISSUE TITLE
App crashing at random

### ISSUE THREAD

**Issue by Fairweather-Furry** [TylerWilliamson/QuickWeather#153]
App was running fine until recently. Now the app closes itself without error when opened. Tried to uninstall and reinstall, installation works fine, app closes once reaching the main screen. Pixel 7a with Android 14.

**Comment by TylerWilliamson** [comment]
Thanks for reporting this issue. I see your crashes in the Play Store crash reporter and I should have a fix out soon. I had included some logic to retry getting radar data if there was any temporary issues, but this logic created instability and random crashes. I'll be reverting that code

**Comment by TylerWilliamson** [comment]
This issue should be fixed in [2.6.9](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.9). Please let me know if you encounter the issue again.

**Comment by Fairweather-Furry** [comment]
Can confirm, fixed. Thank you
