### ISSUE TITLE
Open-meteo pressure

### ISSUE THREAD

**Issue by shed40** [TylerWilliamson/QuickWeather#156]
When using open-meteo, the pressure reading in the top display is showing Surface Pressure, it is normal practice to display pressure as Sealevel Pressure, the difference is around -1mb per 8m in altitude and can cause confusion when comparing places with different heights above sea level.
Otherwise this is a great app
Graham.

**Comment by TylerWilliamson** [comment]
Thank you for reporting this! Should be a quick fix
