### ISSUE TITLE
"Feels like" is showing no temperature value

### ISSUE THREAD

**Issue by geesquer4u** [TylerWilliamson/QuickWeather#160]
![Screenshot_20240515_134114](https://github.com/TylerWilliamson/QuickWeather/assets/87978848/f5ce2d19-40cd-497a-ba11-8bfbaef35526)

**Comment by geesquer4u** [comment]
If the font settings of system are kept little bigger. This is accesibility issue

**Comment by TylerWilliamson** [comment]
I am able to replicate this issue. Should not be a difficult fix. Thank you for reporting it!

**Comment by geesquer4u** [comment]
Forgot to add reference screenshot but yourself had replicated the issue from your end. Anyway updated reference image in old comment. Thanks much developer. I had tried some apps in past few months and ended up using yours.

**Comment by TylerWilliamson** [comment]
Fixed in [2.6.11](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.11)

**Comment by geesquer4u** [comment]
Hi. Now i think there can be enhancements made lookwise. If you see, the ecpanded view now has feels like value but the icons & fonts are big & small. 
![Screenshot_20240729_155638](https://github.com/user-attachments/assets/1f57ed86-e47a-4145-8b35-88b5a6b631cd)
