### ISSUE TITLE
Time indicator with animation

### ISSUE THREAD

**Issue by batje** [TylerWilliamson/QuickWeather#161]
This is not a bug but a request. In the map animation, there is no way to see what the time is of each frame. I still dont know if this is a prediction or based on passed actuals.

Either  clock, or a tiny synced indicator in the rain forecast control would be great.

Kind regards,

Reinier

**Comment by TylerWilliamson** [comment]
There is a time shown when the user moves the slider at the bottom of the radar, but I will also make it shown when the animation is playing

**Comment by TylerWilliamson** [comment]
Added in [2.6.11](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.11)

**Comment by TylerWilliamson** [comment]
Duplicate #65
