### ISSUE TITLE
Graphene + gadgetbridge + infinitime

### ISSUE THREAD

**Issue by sbe-arg** [TylerWilliamson/QuickWeather#163]
I cannot get weather notifications to work on pinetime infinitime 1.14

Probably nothing wrong with quick weather but I'm running out of ideas at the moment.

Quick weather on its own works and I have the gadgetbridge extension enabled.
Gadgetbridge works fine for all other non weather notifications.
No error logs on either app.

**Comment by TylerWilliamson** [comment]
I am not familiar with infinitime, but I would recommend checking all the permissions for the app. In particular, the notification permissions and notification channel settings if the error is just with the notifications. If you are also not seeing the weather information in Gadgetbridge, it could be that the background service for QuickWeather is not running or failing. I could help check your QuickWeather settings if you want to post a screenshot of your settings here and whether the location is "My Location" (your current GPS location) or a fixed location like a city

**Comment by TylerWilliamson** [comment]
I noticed that you also submitted the "auto-start at boot" issue, so I would assume that the issue is that the background job is either not running or is failing as that is what starts at boot and also updates Gadgetbridge and the notifications. If there is no issue with the in-app settings, I would look at the system settings regarding background services and notifications

**Comment by sbe-arg** [comment]
Is there an easy way to verify that gadget bridge is getting the weather info from quickweather without using a device in gadgetbridge? I should probably raise this question in gadgetbridge repos if this is not the right place.

**Comment by sbe-arg** [comment]
Just found that under badgetbridge menu > debug > Show cached weather

shows the correct weather info I guess the problem is with the device at this point.
