### ISSUE TITLE
Display temperature in the phone status bar

### ISSUE THREAD

**Issue by vasilyvaganov** [TylerWilliamson/QuickWeather#170]
It would be great to implement something like this (screenshot from the Yandex Weather app)

![Screenshot_20240804-232052](https://github.com/user-attachments/assets/ea9920f4-f5dd-413c-87f1-dc74d889510e)

**Comment by TylerWilliamson** [comment]
Thank you for the suggestion, but I do not believe it fits with the design of QuickWeather

Duplicate #154
