### ISSUE TITLE
Weather only shows as celcios not fareinherent 

### ISSUE THREAD

**Issue by Stev-lang** [TylerWilliamson/QuickWeather#179]
When connecting to watch via gatebridge

**Comment by TylerWilliamson** [comment]
This is not an issue with QuickWeather. The temperature is sent to Gadgetbridge in Kelvin. You may need to change a setting on your watch, or Gadgetbridge to use Fahrenheit over Celcius. If you cannot find such a setting, I would recommend opening a ticket in the Gadgetbridge repository for them to investigate and resolve.

**Comment by Stev-lang** [comment]
Ok thanks On 27 Sept 2024 18:38, Tyler Williamson ***@***.***> wrote:
This is not an issue with QuickWeather. The temperature is sent to Gadgetbridge in Kelvin. You may need to change a setting on your watch, or Gadgetbridge to use Fahrenheit over Celcius. If you cannot find such a setting, I would recommend opening a ticket in the Gadgetbridge repository for them to investigate and resolve.
