### ISSUE TITLE
Openweather api not working

### ISSUE THREAD

**Issue by 31337-4554551n** [TylerWilliamson/QuickWeather#180]
When trying to add the new Openweather api key it gives a "quick weather requires a call by call subscription". But testing the key in a Web browser using their test URL gives a correct result.

Unable to use Openweather api

**Comment by TylerWilliamson** [comment]
Hello, new API keys sometimes take up to a few hours to activate. Please retry the API Key. If you are still having issues, please post the "test URL" that you are using. Note that the "One Call By Call" subscription is different from the default "weather" API.

**Comment by TylerWilliamson** [comment]
If you are still experiencing this issue, please respond with the information in the previous comment and I will reopen the issue

**Comment by 31337-4554551n** [comment]
Thank you,
My apologies, I'm travelling right now, hence the need for weather haha.

api.openweathermap.org/data/2.5/weather?id=524901&appid=KEYHERE

Is what's on their documentation. I signed up for their new 3.0 key, and the one they gave me works on this URL, even though URL has 2.5 in it, not sure what that's about.

**Comment by TylerWilliamson** [comment]
That url tests the default "weather" API. QuickWeather requires the "One Call By Call" subscription, which is an add-on. You can sign up for it by clicking Subscribe under "One Call API 3.0" on [this page](https://openweathermap.org/api). Alternatively, you may use the Open-Meteo provider which does not require an API Key

**Comment by 31337-4554551n** [comment]
Thank you, I'll try that.
What does that api provide that the weather one doesn't, and that makes the free weather one not worth supporting?

**Comment by TylerWilliamson** [comment]
Weather alerts. And the "One Call" API is free up to the daily limit, which a single user should not hit during normal use.

If you wish to use a completely free provider, and are willing to not receive weather alerts, Open-Meteo is available.
