### ISSUE TITLE
Cannot add additional locations

### ISSUE THREAD

**Issue by living180** [TylerWilliamson/QuickWeather#187]
I am using QuickWeather on GrapheneOS, based on Android 15.  I recently upgraded to QuickWeather 2.7.4 because of issue #184.  Since then, however, I am no longer able to add any locations besides my current location.  In the Edit Location dialog I can enter the Location Name, Latitude, and Longitude, but even with all the fields populated the only buttons in the dialog are SEARCH and CANCEL.  Clicking SEARCH takes me to the Search For Location dialog, and CANCEL takes me back to the Locations screen.  I have not found any way to actually save a new location, which significantly limits this version's usefulness.

**Comment by TylerWilliamson** [comment]
That is a very odd issue. There should be a third button, labeled "ok", like this:
![image](https://github.com/user-attachments/assets/abfa9de7-b8b1-436f-8386-0ec426627a6a)

Could you take a screenshot to show me what you are seeing?

**Comment by TylerWilliamson** [comment]
Nevermind, I found the issue. I added a feature to hide the "search" button on devices like yours that do not have a geocoder and cannot search. However, I copy/pasted the wrong button to hide, and it instead hid the "ok". I'll push a fix shortly

**Comment by TylerWilliamson** [comment]
Fixed in [2.7.5](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.7.5). Please let me know if you get a chance to test this.

**Comment by living180** [comment]
That fixed it - thanks so much for the very quick response!
