### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by Angenios** [TylerWilliamson/QuickWeather#19]
I just registered to OpenWeatherMap and I generated a key, but QuickWeather does not recognize it as a valid API key.

**Comment by TylerWilliamson** [comment]
Please try re-entering the API key and double check that you have entered it in exactly as it appears on OpenWeatherMap. If if still doesn't work, you can try generating a new key or regenerating that key. If you are still having this issue, could you please tell me what device you are using and what android version you are on, and if there are any error messages that appear.

**Comment by k3b** [comment]
i had the same problem. 

I tried the same key a few hours later and then it worked.

So i assume OpenWeatherMap needs some time to update it-s key-database.

@Angenios is the key still invalid?

**Comment by TylerWilliamson** [comment]
@Angenios Did any of the above solutions resolve your issue? If I do not hear back from you after 3 days I will close this issue and assume your issue was resolved.

**Comment by Angenios** [comment]
Yeah, I confirm it was just a matter of minutes: I tried the same key a few moments later and it worked. Sorry if I'm answering so late, I did not receive notifications.
