### ISSUE TITLE
Feature request: Tighten UI to fit all text

### ISSUE THREAD

**Issue by huuhaa** [TylerWilliamson/QuickWeather#190]
Currently UI has daily view under radar, it has some room for improvements since fields currently takes so much space that not all text can fit at weather decription field. Wouldn't be such an issue if it wouldn't be the case at most of the time.

Partally relating this & giving more room & looking better at currect spelling point of view would also be that not every word would be forced to start with big letter. I change that when doing translation part, but still at app translation is Like This, instead like this.. Same goes sure at current weather description.

How to get more horizontal space at vertical screen then? Well maybe some of those mentioned above, font size customization and.. One thing I've been wondering is word Today taking relatively long space (which effects position of weather icons), but hard to replace with "Now" either, cause different thing.. Sure currently at app what is visible, is well visible even if bad eyesight (I assume), but would be nice is some improvement to that could be found.

**Comment by TylerWilliamson** [comment]
I appreciate the ideas, but those design decisions were deliberate and I will not be changing them.
