### ISSUE TITLE
Onboarding is a bit weird

### ISSUE THREAD

**Issue by xeruf** [TylerWilliamson/QuickWeather#20]
- The dots at the bottom feel like navigation, but an onboarding is a rather linear process
- The policies at the bottom scroll separately rather than the whole screen, making it really awkward to scroll properly

![Screenshot_20210826-134009_QuickWeather](https://user-images.githubusercontent.com/13354331/130956932-c6a9b67b-999b-44c6-b357-7c25fe575ba8.jpg)

**Comment by TylerWilliamson** [comment]
[Version 2.0.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.0.0) has been released, which should resolve this bug. Please verify and let me know. If there is no response after 7 days I will close this bug

**Comment by xeruf** [comment]
If it was available in F-Droid I would love to test, but it isn't yet :/

**Comment by TylerWilliamson** [comment]
Version 2.0.0 should be available on [F-Droid](https://f-droid.org/en/packages/com.ominous.quickweather/) now.

**Comment by xeruf** [comment]
Yep, seems all fine now :)
