### ISSUE TITLE
Enhance information visualization at a glance in graphs

### ISSUE THREAD

**Issue by xeruf** [TylerWilliamson/QuickWeather#22]
I am coming here from the https://weawow.com app, which has many nice features but feels bloated and slow. I would love to see some of its nice graph styles adopted here :)

What I miss most are
- weather icons below the hourly forecast graph (for example so I can see whether it is cloudy or sunny and decide whether it is worth visiting a lake)
- the bar diagram in the day forecast which enables you to see temperature differences at a glance

You can see these in the screenshots below or on their website.

![Screenshot_20210826-135958_Weawow](https://user-images.githubusercontent.com/13354331/130961208-7dfafb40-811f-452d-987f-10b42e8d5802.jpg)
![Screenshot_20210826-140014_Weawow](https://user-images.githubusercontent.com/13354331/130961213-5896a1b3-28f2-4dbc-a127-1487e36f3684.jpg)

**Comment by TylerWilliamson** [comment]
[Version 2.0.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.0.0) has been released with the above feature
