### ISSUE TITLE
Error connecting to GeoCoder

### ISSUE THREAD

**Issue by sim6** [TylerWilliamson/QuickWeather#24]
I'm getting the "Error connecting to GeoCoder" when I'm trying to add locations.

**Comment by TylerWilliamson** [comment]
The GeoCoder translates text like "Atlanta, GA" to a set of geographic coordinates. This feature requires the Google Play Services. Does your device have Google Play Services?

If your device does not have Google Play Services, you can use the "Manual" setting to manually add locations by geographic coordinates.
