### ISSUE TITLE
3 days graph

### ISSUE THREAD

**Issue by sim6** [TylerWilliamson/QuickWeather#25]
Please, cloud you add an option to expand the graph to 3 days?

**Comment by TylerWilliamson** [comment]
At this time I do not have any plans to expand the graph to multiple days. In the next update, there will be a "Forecast" feature where it will be possible to view the graph for a specific day. Please note that OpenWeatherMap only provides 48 hours of hourly data. After that point, the forecast graph will only be able to show the forecasted weather every 3 hours.

**Comment by TylerWilliamson** [comment]
[Version 2.0.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.0.0) has been released which includes daily graphs with hourly data for the first 48 hours, and data every 3 hours for the 3 days after that
