### ISSUE TITLE
Feature to add current location to locations list

### ISSUE THREAD

**Issue by sim6** [TylerWilliamson/QuickWeather#26]

**Comment by TylerWilliamson** [comment]
This feature will be implemented in a future release

**Comment by TylerWilliamson** [comment]
I have implemented this feature as part of [version 2.2.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.2.0), which is currently available on GitHub or on Google Play Store as a Beta release. Please give it a test and let me know if you have any feedback. I expect to fully release this version in a few days.

**Comment by sim6** [comment]
Thank you!
