### ISSUE TITLE
Cache weather data

### ISSUE THREAD

**Issue by xeruf** [TylerWilliamson/QuickWeather#29]
For me this was implied by the branding of the app, but apparently it is not so far: When I am in an area with bad internet and have already fetched the weather, show me the cached one until new data is available.

**Comment by TylerWilliamson** [comment]
I will consider this enhancement, but it will likely be a fairly heavy lift as the app would need to cache the latest current and forecast API calls for each location. It may make more sense to have an "offline mode" toggle where it will cache all those calls and not fetch new weather until that mode is disabled (presumably, when the user has internet access again). The major downside would be if the user relies on the app for weather alerts, which can be mitigated with a snackbar notification. Let me know if you have any thoughts on this, or if it would fit your use case

**Comment by xeruf** [comment]
> but it will likely be a fairly heavy lift as the app would need to cache the latest current and forecast API calls for each location

Why is that a heavy lift?

**Comment by DJCrashdummy** [comment]
yes, IMHO a more or less proper "offline mode" would be a good idea!
**but** not a manual one... i imagine it like that:
- first don't show the cryptic notification every time when i disable my internet connections for some time, it's driving me nuts!
- have the weather data cached and display them even when i'm not online.
as it might be the case that this data is outdated, mark the time/date somehow (different color?) to clearly indicate that the data might be "stale".
- let the user choose a time span after which the data should be considered outdated/stale and the mentioned indication would kick in.
- IMHO this time span could/should also be used to gather new data.
-> this way - depending on the default - the server requests may even be reduced... i have no idea how often the app polls now (especially when the notification is enabled); but e.g. i'm usually only interested in forecasts for the week, and as they are not changing that quickly, i'm ok with updates every ~6 hours or the like.
- if there was no internet connection at the last try, refresh the data as soon as there is one again to have "current" data in the cache again.

**Comment by TylerWilliamson** [comment]
Thanks for the feedback. I've already started work on the caching and it will be a part of the next release. In addition to the existing in-memory cache, there will also be a file-based cache storing the latest weather data for each location. If you enable the weather alerts, persistent weather notification, or gadgetbridge extension, but do not have internet access, it will display an error message when it fails to get the weather (opening the app will show the latest available weather, and display an error in the app that it could not update the weather). When your internet access is restored, that background job will succeed as normal.

There will not be any new user options. It should be a seamless user experience.

Also, I will not be removing the error notification. I believe it is a safety feature to ensure that the user knows that they are not currently receiving weather alerts and should not rely on the app for their safety in case of weather emergencies. Should you still wish to not see that notification, follow either option outlined in this issue: #95

**Comment by xeruf** [comment]
Personally I am currently on https://github.com/breezy-weather/breezy-weather but good to see progress here :)

**Comment by TylerWilliamson** [comment]
Added in [2.7.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.7.0)
