### ISSUE TITLE
Cannot remove location

### ISSUE THREAD

**Issue by Gene-W** [TylerWilliamson/QuickWeather#31]
Hello,

When I try to remove or edit a location from the list, after saving it reverts back to previous information on an edit, or doesn't remove when deleted.

Using LineageOS + microG, OnePlus6.

**Comment by TylerWilliamson** [comment]
I am able to replicate this bug and will work on it. The fix should be included in the next release, coming in a few days

**Comment by Gene-W** [comment]
Thank you, Tyler. And thanks for your work on this app, I appreciate the very clean design and the reliability of the weather information. Nicely done!

**Comment by TylerWilliamson** [comment]
I believe I have fixed the issue. Could you please attempt to replicate the bug with the attached zipped debug APK? If there are no issues, I'll publish it tomorrow to GitHub and the Google Play Beta channel (and to the production channel a few days later). It will roll out to F-Droid whenever they next update their repo.

[QuickWeather-2.1.1-DEBUG.apk.zip](https://github.com/TylerWilliamson/QuickWeather/files/8545789/QuickWeather-2.1.1-DEBUG.apk.zip)

**Comment by TylerWilliamson** [comment]
I see that you are using "microG". The Geocoder is unfortunately tied to Google Play Services and I am unsure if the "microG" implementation includes it. Were you able to use the geocoder before? You should still be able to use the "manual" button to fill out a location manually by entering a name and lat/long

**Comment by Gene-W** [comment]
That worked, I was able to manually add several locations and successfully remove them.

I thought the geocoder previously worked using the F-droid version on microG, but I just checked again and it is not. Its also possible I added them manually and don't remember! It does find current location when I allow it and manually adding locations are no problem.

**Comment by TylerWilliamson** [comment]
Thanks for the update! I'm marking this fixed as [Version 2.1.1](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.1.1) is now released. It will make its way to F-Droid when they update their repo.
