### ISSUE TITLE
Bug: QuickWeather's Radar view does not work with Bromite's Webview 

### ISSUE THREAD

**Issue by daffydock** [TylerWilliamson/QuickWeather#37]
App works fine with Chromium's webview, or Bromite's Chromium Webview is used, which has some modifications but it is for the most part vanilla. Bromite's Webview is an enhanced, privacy focused implementation of webview and the radar window remains gray upon launching the app.

The rest of the app works fine. When started, the radar window shows the Leaflet link but it stops there. Nothing else seems to load. 

Worth noting, it is the F-Droid version being used here. Have not tested with Play store version. 

If this is something that could be resolved then that would be ideal, if possible.

**Comment by TylerWilliamson** [comment]
I'm not too familiar with Bromite. Would you be able to collect app logs to see if there are any messages from WebView? My radar runs as a local server (on localhost) and connects to external datasources for the radar (Rainviewer) and map. It also uses Javascript. Bromite might block either or both. Let me know if you get any additional information. I will also look into replicating the issue

**Comment by TylerWilliamson** [comment]
I have a planned "fix" for this coming in the next release. I plan to replace the radar webview with a native OpenGL radar. This should resolve the issue you are seeing.

**Comment by TylerWilliamson** [comment]
Issue should be resolved in the latest release [2.3.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.3.0). This release is currently a "Pre-release" on GitHub, and in "Open Beta" on Google Play. Please give it a test and see if it your issue has been fixed.

**Comment by daffydock** [comment]
Tried the newest version and yes, it works 100%. 
I know you closed the issue but I wanted to let you know that it is "fixed." Also, to say Thanks. 

Cheers.
