### ISSUE TITLE
Real Feel Temperature

### ISSUE THREAD

**Issue by tieu1991** [TylerWilliamson/QuickWeather#39]
It would be nice to have the real feel temp displayed.

**Comment by TylerWilliamson** [comment]
I did some preliminary research and there seems to be a variety of different "real feel" calculations which take into account heat index and wind chill. I am interested in this data though. I'll consider this enhancement

**Comment by tieu1991** [comment]
According to the openweathermap api it already return "feels_like" data.

**Comment by TylerWilliamson** [comment]
Indeed it does. That makes things easier

**Comment by TylerWilliamson** [comment]
Added in [2.2.3](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.2.3)
