### ISSUE TITLE
Feature: Add location indicator to map

### ISSUE THREAD

**Issue by ryester19** [TylerWilliamson/QuickWeather#40]
Current behavior right now looks to be that the map is centered to where your GPS location is. However, there is no indicator on the map visualizing where you are.

Can you please add some kind of indicator to the map showing where you are? This will help with reading the radar if you ever scroll away from the center or expand the radar fullscreen. Thank you.

**Comment by TylerWilliamson** [comment]
I plan to address this in the next release. Instead of a icon at the center of the map, the map will have an icon to let the user re-center the map. I know this isn't the exact feature you were asking for, but I believe it fits more with the design language of QuickWeather and other apps with maps

**Comment by TylerWilliamson** [comment]
Issue should be resolved in the latest release [2.3.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.3.0). This release is currently a "Pre-release" on GitHub, and in "Open Beta" on Google Play. Please give it a test and see if it your issue has been fixed.

**Comment by Discostu36** [comment]
I'm on 2.3.4 and there is still no icon on the map.

**Comment by ryester19** [comment]
> I'm on 2.3.4 and there is still no icon on the map.

I don't think they added an icon, just gave us the ability to center the map at your location

**Comment by Discostu36** [comment]
Ah, sorry, I misunderstood the comment above. I don't think that it solves the issue as the app allows to view data on locations different from the one I'm currently at.

**Comment by TylerWilliamson** [comment]
I am reopening this issue and I will look for a solution which addresses this need and maintains the design aesthetic.

**Comment by TylerWilliamson** [comment]
Added in [2.6.3](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.3)
