### ISSUE TITLE
API key invalid 

### ISSUE THREAD

**Issue by metbic** [TylerWilliamson/QuickWeather#41]
Saw the app in fdroid, it seemed like something worth trying out. I applied for an openweather API key, initial setup page says 'invalid'.  So I generated another API key, again 'invalid'. Setup tells me to wait some hours. One day later, the keys still invalid. Can you please provide me with a working key?

**Comment by TylerWilliamson** [comment]
QuickWeather requires the "Weather" service NOT the new "One Call By Call" service by OpenWeatherMap.

Please confirm that you have an API Key for "Weather" NOT "One Call By Call" [here](https://home.openweathermap.org/myservices). You should see something like this:

![image](https://user-images.githubusercontent.com/8985022/187033504-0661ecdc-ea2f-4e5e-9bf5-5c5d622ff373.png)

If you do not see the "Weather" service, go [here](https://home.openweathermap.org/users/sign_up) and create a new account specifically for the "Weather" service (you can probably add it to your existing account, but it's easier to just create a new one)

**Comment by metbic** [comment]
Like that? 
![Screenshot_20220827-162524](https://user-images.githubusercontent.com/8116828/187034623-bbb8e838-cba2-4acc-9a5d-f1869f422244.png)

**Comment by TylerWilliamson** [comment]
Looks like you should be able to use the API. Copy your API Key again from OpenWeatherMap, and try this URL below with your API Key. If it's successful, try it again in QuickWeather. If there's an error, can you post the error?

https://api.openweathermap.org/data/2.5/onecall?lat=33.44&lon=-94.04&exclude=hourly,daily&appid=YOUR_API_KEY

**Comment by metbic** [comment]
I put my api key into your link and the error looked like that:

{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}

**Comment by metbic** [comment]
Also I want to report that the small red X button to clear the api key input field in the setup pages is non functional. 
![_20220827_164218](https://user-images.githubusercontent.com/8116828/187035287-7d59f836-f167-4175-a593-e2e97b7b0a01.JPG)

**Comment by TylerWilliamson** [comment]
Try this url with your API Key (Trying the new "3.0" version)

https://api.openweathermap.org/data/3.0/onecall?lat=33.44&lon=-94.04&exclude=hourly,daily&appid=YOUR_API_KEY

**Comment by metbic** [comment]
Sorry, both keys didn't work with your 3.0 link neither.

**Comment by TylerWilliamson** [comment]
If you have double-checked the API Key and there are no typos, I would reach out to OpenWeatherMap [here](https://home.openweathermap.org/questions) and confirm that your API Key is activated and that you are able to use the "OneCall API version 2.5". Please let me know what the resolution to this issue is. It appears to only affect new API Keys and may be due to their new OneCall 3.0

**Comment by metbic** [comment]
![Screenshot_20220827-171257](https://user-images.githubusercontent.com/8116828/187036223-bd445abe-0d99-4d00-98de-388564719256.png)
Done.

**Comment by davquar** [comment]
I also have this problem (registered today) and I noticed that replacing `onecall` with `weather` works.

For example, the following URL doesn't work:

> Looks like you should be able to use the API. Copy your API Key again from OpenWeatherMap, and try this URL below with your API Key. If it's successful, try it again in QuickWeather. If there's an error, can you post the error?
> 
> https://api.openweathermap.org/data/2.5/onecall?lat=33.44&lon=-94.04&exclude=hourly,daily&appid=YOUR_API_KEY

But this works: 

`https://api.openweathermap.org/data/2.5/weather?lat=33.44&lon=-94.04&exclude=hourly,daily&appid=YOUR_API_KEY`

**Comment by TylerWilliamson** [comment]
So, what I have gathered is this:

1. OpenWeatherMap came out with the "OneCall" API version 2.5 about 2 years ago, and I updated QuickWeather to use it.
2. They just released "OneCall" version 3.0 and have moved it to its own service. Users can subscribe to both "Weather" and "OneCall" services for free ("OneCall" version 3.0 does require providing OpenWeatherMap with billing information though).
3. New users can only subscribe to OneCall 3.0, but existing users can use OneCall 2.5, until they inevitably turn it off

What does this mean? Well right now, new users cannot use QuickWeather. I will need to push a fix for this, but the fix will not be simple.

Most likely, QuickWeather will require the "OneCall" version 3.0. The other APIs "Current" and "Forecast" do not include the weather alerts nor the hourly data. This will mean that users will have to provide billing information to OpenWeatherMap.

If the user has an older API key, then QuickWeather will attempt to use OneCall version 2.5. If that fails, then it will attempt version 3.0.

If there is sufficient support for QuickWeather to not require OneCall 3.0 (and support for users to not have to provide billing information to OpenWeatherMap), I can work on supporting using the "Current" and "Forecast" APIs only and not "OneCall". A version like this will NOT have weather alerts (neither notifications nor alerts in the app).

**Comment by woheller69** [comment]
I changed my RadarWeather 

https://f-droid.org/de/packages/org.woheller69.weather/

to support OneCall 3.0. Users have to check a box in settings, then the Url will be changed from .../2.5/... to .../3.0/... and everything works again.
According to OWM old keys will continue to work, only new users are affected.
Users should set their limit to 1000 calls/day, then they will not be charged because 1000 calls are free

**Comment by TylerWilliamson** [comment]
Resolved in [2.2.2](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.2.2). QuickWeather will determine which API to use. Users will need either OneCall 2.5, or OneCall 3.0. 2.2.2 is available now on GitHub, will be available in F-Droid when they compile the new version (a few days usually), and will be available on Play Store in a few hours. Please test and let me know if there are any issues
