### ISSUE TITLE
Accessibility: low contrast buttons in dark mode

### ISSUE THREAD

**Issue by davidbtc2009** [TylerWilliamson/QuickWeather#44]
The buttons are very low contrast and hard to see when in dark mode while the text is fine

![Screenshot_20220911-181216_QuickWeather_1_1](https://user-images.githubusercontent.com/67274571/189723859-2a54b86b-11b8-426c-820a-8ecae6a96f8f.png)
![Screenshot_20220912-135306_QuickWeather_1](https://user-images.githubusercontent.com/67274571/189723864-5fb2c5c7-457b-454c-bc10-4bba4561cd8d.png)

**Comment by TylerWilliamson** [comment]
Thank you for pointing this out. I'll adjust the colors for the next release. Is the below coloring easier to read?

![Screenshot_20220915-222729_QuickWeather](https://user-images.githubusercontent.com/8985022/190543658-93ff2508-ee1f-4b99-88df-7eb085208235.png)

**Comment by TylerWilliamson** [comment]
Also to note, this bug only affects devices on versions before Android 12. On Android 12 or higher, the colors are based on the app theme.

![Screenshot_20220915_223403](https://user-images.githubusercontent.com/8985022/190544238-22b4e551-c8e6-40bc-8306-f441d1e231b5.png)

**Comment by davidbtc2009** [comment]
Interesting that this is a <12 issue. To answer your question, yes. That is easier to read

**Comment by TylerWilliamson** [comment]
Resolved in [2.2.3](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.2.3)
