### ISSUE TITLE
Add Gadgetbridge Support [Duplicate]

### ISSUE THREAD

**Issue by mskian** [TylerWilliamson/QuickWeather#45]
your App was really Awesome

if it has Gadgetbridge Support it will be more Benefit for me 
Weather-related wiki - https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather

unfortunately, this app was not maintained it has Gadgetbridge Support - https://github.com/gelin/weather-notification it also uses an OpenWeatherMap API 

For More Reference

- https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather#install-and-configure-weather-notification
- https://github.com/gelin/weather-notification/issues/68

**Comment by mskian** [comment]
Just Noticed it https://github.com/TylerWilliamson/QuickWeather/issues/38 - https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.2.4

still, F-droid has not been Updated the released Version

**Comment by TylerWilliamson** [comment]
Support added for Gadgetbridge in [2.2.4](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.2.4). Should work with Gadgetbridge 0.71.0 or higher. Do note that 2.2.4 and 2.2.5 were recently released and F-droid only updates its apps every so often. Also, Gadgetbridge 0.71.0 was also delayed, but once F-droid updates, it should also get released.
