### ISSUE TITLE
API 2.5 doesn't work 

### ISSUE THREAD

**Issue by hexchills** [TylerWilliamson/QuickWeather#46]
"One Call" plan costs: 0.12 GBP per 100 calls 😞

![screenshot-obfuscated (1)](https://user-images.githubusercontent.com/61146542/196027071-e6cc74f4-639f-4c52-86d6-e4ec77be49a1.jpg)

P.S. My API works with this link: https://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=API_KEY

**Comment by najodleglejszy** [comment]
the first 1000 calls a day are free (which lets you call it once every 90 seconds or so). it's 0.12 GBP for 100 calls once you reach the daily limit.

**Comment by TylerWilliamson** [comment]
QuickWeather requires either the OneCall 2.5 or 3.0 API, not the "Weather 2.5". The OneCall 3.0 has 1000 free API calls per day. After that, you are charged. You can set a custom daily limit in the settings to 1000 (by default its 2000).

![image](https://user-images.githubusercontent.com/8985022/196041035-30e75389-fe2e-4ff2-b842-affcca5dd4b0.png)
