### ISSUE TITLE
Notification Error 2

### ISSUE THREAD

**Issue by Github-contribute** [TylerWilliamson/QuickWeather#53]
If turn off minimize in notification settings, weather information show like this

![Screenshot_20221101-195040_Neo Launcher_1_1](https://user-images.githubusercontent.com/106362356/199256973-57aa93d9-562a-47aa-b84a-a79002da2e0e.png)

**Comment by TylerWilliamson** [comment]
This is not an error. The notification is designed to be minimized and expanded. If you try to force it to be expanded, it simply does not work as implemented.
