### ISSUE TITLE
Adopt Material You UI

### ISSUE THREAD

**Issue by Github-contribute** [TylerWilliamson/QuickWeather#55]
Pls adopt material you UI. Now, UI looking old and 
Adopt material you icon of this app.

https://play.google.com/store/apps/details?id=com.kokoschka.michael.weather

**Comment by TylerWilliamson** [comment]
The style of QuickWeather is intentional. At this time I will not be refactoring the entire app to make it "Material You". Should you want a "Material You" weather app, I suggest that you use app that you linked.
