### ISSUE TITLE
Feature request: Hide weather radar

### ISSUE THREAD

**Issue by iamtherobin** [TylerWilliamson/QuickWeather#56]
Can we get a simple option to hide the weather radar? It takes up a lot of space and I don't really care for that info (also I am a bromite user and it does not work for me personally anyways). Would be nice to be able to get it out of the way.

**Comment by TylerWilliamson** [comment]
I like the idea of this, but with additional customization and re-ordering. It would take some effort on my part to figure out the best way to do it.

Also, next version, the radar will be rendered locally, and not in a browser view, so you should be able to at least use it

**Comment by sebastianha** [comment]
I second this idea.
I would make the app open "more quicker". For me sometime it takes seconds to load the rain data and it does not indicate if it is just clear sky or it is still loading. Also it would save some data.

BTW: Great app, kepp up the great work!

**Comment by TylerWilliamson** [comment]
> I second this idea. I would make the app open "more quicker". For me sometime it takes seconds to load the rain data and it does not indicate if it is just clear sky or it is still loading. Also it would save some data.
> 
> BTW: Great app, kepp up the great work!

In version [2.4.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.4.0) the radar will begin loading quicker. I may also add an indicator that the radar is still loading in a future release.

Also, while I am still working on the additional customization, you may be interested in the radar quality toggle that I introduced in version [2.4.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.4.0) that can be used to reduce the data usage.

**Comment by nutpantz** [comment]
I also would love to see radar optional.  I just don't use it or i expect ever will

**Comment by TylerWilliamson** [comment]
Added in [2.5.5](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.5.5). There is a new "Disabled" option in the Advanced Settings for "Radar Quality" that can be used to hide the radar

**Comment by sebastianha** [comment]
Does it then also disabled the network requests beloning to the map? Or does it only hide the UI element?

**Comment by TylerWilliamson** [comment]
Both the UI element and all network requests for the radar are blocked

**Comment by TylerWilliamson** [comment]
As of [2.6.1](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.1), this feature has moved to the "Layout" menu in the "UI" section of Settings. Radar can be disabled by opening the "Set Layout" dialog, and unchecking the switch for Radar. Users who previously disabled the radar in the Advanced Settings should see it disabled in the "Set Layout" dialog automatically
