### ISSUE TITLE
Regression in 2.2.7: Adding location from map doesn't work with locale where , is decimal point

### ISSUE THREAD

**Issue by nikobockerman** [TylerWilliamson/QuickWeather#57]
This regression is likely related to the fix made for #48 in 2.2.7 version. The fix there works and adding `,` is now possible and manually adding location coordinates works. However, a regression was introduced with that change when selecting a new location from map.

Now when I add a new location from map and select a location from somewhere in Germany near Berlin, I get to the `Edit Location` view with these coordinates:
Latitude: `52471786038477008,000`
Longitude: `13390451408922674,000`

I should have gotten these coordinates instead:
Latitude: `52,471786038477008`
Longitude: `13,390451408922674`

In 2.2.6 selecting location from map did open the `Edit Location` view with the correct coordinates.

**Comment by TylerWilliamson** [comment]
Issue confirmed. Fix should be included next version

**Comment by TylerWilliamson** [comment]
Issue should be resolved in the latest release [2.3.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.3.0). This release is currently a "Pre-release" on GitHub, and in "Open Beta" on Google Play. Please give it a test and see if it your issue has been fixed.

**Comment by nikobockerman** [comment]
I built it myself from the repo and tested that way. This issue was fixed there. Thanks!
