### ISSUE TITLE
[Feature Request] intent filter for geo: view/send as "Show Weather at this location"

### ISSUE THREAD

**Issue by k3b** [TylerWilliamson/QuickWeather#6]
Usecase:

* From your navigation app press "view location" or "share location" or "open location in external app"
* Android shows you all apps that support geo: - uris
* Select "Show Weather at this location with QuickWeather"
* you will see the weather of you holliday destination in QuickWeather.

This feature could work with [many geo-aware apps](https://github.com/k3b/k3b-geoHelper/wiki/Android-Geo-aware-apps) like [Osmand](https://github.com/osmandapp/Osmand)

For details how this could be implemented see https://github.com/k3b/k3b-geoHelper/wiki/Android-Geo-howto.

@TylerWilliamson : i can do the implementation for you and send you a merge request, if you like

**Comment by TylerWilliamson** [comment]
QuickWeather currently utilizes a set of saved locations. This request would require architectural changes to allow for arbitrary locations and would likely not be a simple request. However, this request is interesting and I will consider working on it.

**Comment by TylerWilliamson** [comment]
Hello @k3b I have implemented this request in the version 1.3.4 of QuickWeather. This version is currently in Beta on Google Play Store. I have also attached the zipped APK here. You should be able to open "geo" links with QuickWeather and it will automatically open to the location settings with an Edit dialog for the location you are opening. Then you can name the location and save the settings to view the weather at that location. 

Could you let me know if it works as intended with your geo-aware apps? If there is no response after a week, I will go ahead and promote this release to Production.

Thank you

[QuickWeather-1.3.4.apk.zip](https://github.com/TylerWilliamson/QuickWeather/files/6951275/QuickWeather-1.3.4.apk.zip)
