### ISSUE TITLE
Time label lacks proper format 

### ISSUE THREAD

**Issue by mkarmona** [TylerWilliamson/QuickWeather#60]
Firstly, great android app! This is a minor enhancement but for the sake of keeping track though. 

Time for intraday card needs hour minutes formatting.
![Screenshot_20221119_131621_QuickWeather.jpg](https://user-images.githubusercontent.com/5394232/202853853-f239fa6f-a01e-42fe-907d-7194036840f2.jpg)

**Comment by TylerWilliamson** [comment]
Yep, sorry for that oversight. I'll include a fix next version

**Comment by baack** [comment]
Probably this one should be closed?

**Comment by TylerWilliamson** [comment]
> Probably this one should be closed?

Unfortunately, not yet. I began working on this prior to pausing work on QuickWeather and I found that this was a bit more difficult than I originally anticipated. I then got distracted by other issues and did not work on this. I have resurrected my old work and should have a fix next version though

**Comment by TylerWilliamson** [comment]
Fixed in [2.5.2](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.5.2)
