### ISSUE TITLE
Weird weather radar map card size

### ISSUE THREAD

**Issue by mkarmona** [TylerWilliamson/QuickWeather#61]
Not sure if this bug comes from orientation changes or not as I find hard to reproduce it again. 

![Screenshot_20221121_131154_QuickWeather.jpg](https://user-images.githubusercontent.com/5394232/203131201-b4fe4a7a-15f4-4727-9848-2c0ea566c7a2.jpg)

If I click on maximise and restore the problem remains but it disappears as soon as I pull down to refresh the view 

![Screenshot_20221121_131204_QuickWeather.jpg](https://user-images.githubusercontent.com/5394232/203131432-dd3b2772-975f-4212-94f1-8bdbe8da82a4.jpg)

**Comment by TylerWilliamson** [comment]
Interesting. I'd say it's most likely related to orientation change since there is a different card height for horizontal orientation. I'll look into it

**Comment by TylerWilliamson** [comment]
This should be resolved in version [2.6.1](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.1). Please let me know if you encounter it again
