### ISSUE TITLE
Free OpenWeatherMap API Key doesn't work, requires paid subscription?

### ISSUE THREAD

**Issue by surfrock66** [TylerWilliamson/QuickWeather#64]
Recently installed this and am setting up my API key.  I've made my API key, it's in and valid, it's been a few days:

![image](https://user-images.githubusercontent.com/1345467/211379844-6d7b4cde-591f-4ff4-b9a6-baa88cbb8a65.png)

When I enter this into QuickWeather and try to test the API key, I get an error saying "Quickweather requires the OneCall Subscription"

![image](https://user-images.githubusercontent.com/1345467/211380161-599d3c9d-b91b-4c8d-bb77-9ce38a902581.png)

As far as I can tell, that API is only available in the "per-call" subscription?  https://openweathermap.org/api/one-call-3

Is this a change or something, can this not work with a free API key anymore?

**Comment by TylerWilliamson** [comment]
The One-Call API is free for the first 1000 calls per day, but if you go over that, you would pay. See [OpenWeatherMap's Pricing](https://openweathermap.org/price). After subscribing you can set a daily limit of 1000 in your user settings if you want to ensure you cannot go over the free tier.

**Comment by surfrock66** [comment]
Understood, just set that up.  It was a little confusing from the README; it may be worth clarifying, since the doc said set up a free API key I didn't understand I had to move forward on a subscription that requires a credit card even if you don't get to the point of billing.

**Comment by TylerWilliamson** [comment]
Thank you for the suggestion, I will add that clarification to the README, Play Store, and F-Droid listings at a later time. Since your issue is resolved, I will go ahead and close this issue. Thank you
