### ISSUE TITLE
{Feature Request] Add an updated time to radar

### ISSUE THREAD

**Issue by shortwavesurfer2009** [TylerWilliamson/QuickWeather#65]
Right now you have to tap and hold the timeline to see the last update time. I suggest a "updated at" (time)

**Comment by TylerWilliamson** [comment]
This would be a good enhancement for QuickWeather. I'm not sure how I want to implement it though. Also I do not expect to work on QuickWeather until later this year.

**Comment by mrondr** [comment]
Could I suggest to always show the timestamp of the frames in the animation? This solves the issue above (and provide the time reference of the animation, which is what brought me here while looking for it)

**Comment by radicalrusty** [comment]
> Right now you have to tap and hold the timeline to see the last update time. I suggest a "updated at" (time)

I didn't even realize that this information was hidden like that. Cool to know, and I'd definitely be excited to see that get updated

**Comment by TylerWilliamson** [comment]
Added in [2.6.11](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.11)
