### ISSUE TITLE
Show sunrise/sunset times

### ISSUE THREAD

**Issue by new2f7** [TylerWilliamson/QuickWeather#66]
It would be nice to see sunrise and sunset times in the list that opens when you tap on the temperature.

**Comment by TylerWilliamson** [comment]
This is something I can see being useful, and the data is available from OpenWeatherMap. I'll likely include this when I implement being able to choose the weather cards and their order in the main screen

**Comment by radicalrusty** [comment]
> This is something I can see being useful, and the data is available from OpenWeatherMap. I'll likely include this when I implement being able to choose the weather cards and their order in the main screen

When you implement the weather cards, could we possibly have an option to disable the radar card and put a radar button somewhere convenient instead (my location suggestion would be the top bar on the right side) and the radar button would take you to the full-screen radar.

**Comment by TylerWilliamson** [comment]
The radar card can already be disabled - see [this issue](https://github.com/TylerWilliamson/QuickWeather/issues/56)

I will not be adding a "radar button".

Please keep each issue on topic to reduce clutter - this issue should primarily be regarding a sunrise/sunset card

**Comment by cvoinf** [comment]
It would be great if quivkweather passed the sunset/rise time Fürther to gadgetbridge.

Perhaps the times can be calculated by quickweather:

[https://github.com/juanmatola/sunrise-sunset-calc](https://github.com/juanmatola/sunrise-sunset-calc)

**Comment by TylerWilliamson** [comment]
That is a good point. I'm working on designing the sunrise/sunset card now, but in the next version, the sunrise, sunset, moonrise, moonset, and moon phase will be passed along to Gadgetbridge. Note: Open-Meteo does not provide moon rise, moon set, or moon phase, but I may be able to calculate them by adapting [this code](https://github.com/signetica/MoonRise)

**Comment by TylerWilliamson** [comment]
Added the optional Sun and Moon card in [2.6.5](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.5)

**Comment by new2f7** [comment]
Beautiful, thank you very much!
