### ISSUE TITLE
Wind speed always showing 0 on bangle.js watch with Gadgetbridge

### ISSUE THREAD

**Issue by stweedo** [TylerWilliamson/QuickWeather#68]
I am using the QuickWeather app to send weather data to my bangle.js watch via Gadgetbridge. Everything works correctly, except the wind speed value always displays as 0 on the watch, even though QuickWeather is broadcasting a value above 0.

The wind speed works correctly when using the Weather Notification app with Gadgetbridge, so I believe the issue is specific to QuickWeather.

Expected behavior:
The wind speed value should display correctly on the bangle.js watch.

Actual behavior:
The wind speed value always shows 0 on the bangle.js watch, despite QuickWeather broadcasting a non-zero value.

Additional information:

    QuickWeather version: 2.3.2
    Gadgetbridge version: 0.71.2
    Bangle.js watch Weather app version: 0.25
    Android OS version: 12

Please let me know if you need any additional information or if there are any troubleshooting steps you would recommend. Thanks

**Comment by TylerWilliamson** [comment]
That certainly seems like a bug to me. I'll look into it when I resume development

**Comment by TylerWilliamson** [comment]
Hello, I finally had some time to investigate this, but I will need a bit of help testing. It appears that GadgetBridge is looking for wind speed in km/h. Internally, QuickWeather uses mph and converts it to show the user, but what it was sending to GadgetBridge was unconverted. I have added the conversion, but I do not have a way to test this. If this is indeed the correct fix, then you should currently see that the windspeed is approximately 60% lower than it should be, but it shouldn't be zero. If it's always zero, then this will not fix the issue. Please let me know if you can look into this. If not, I'll push the fix anyway in the next minor release

**Comment by stweedo** [comment]
Hi Tyler,

About a week or two ago I noticed it started showing approx 60% of what QuickWeather would show. Maybe something was updated in Gadgetbridge or BangleApps.

If you need someone to test your new conversion code I would be happy to help.

Thanks for looking into this!

**Comment by TylerWilliamson** [comment]
Thanks for the quick information! That is exactly what I was hoping to hear. I'll look to push a fix in the next couple of days.

**Comment by TylerWilliamson** [comment]
Resolved in [2.3.3](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.3.3)
