### ISSUE TITLE
Scrollable graph

### ISSUE THREAD

**Issue by Donkey-Doug** [TylerWilliamson/QuickWeather#7]
Make it possible to scroll the graph to see the weather not only for today but also the upcoming days.

**Comment by TylerWilliamson** [comment]
A scrollable graph is planned as part of a future release. Please note that OpenWeatherMap only exposes 48hours of hourly weather (currently 24 are shown).

**Comment by TylerWilliamson** [comment]
Added in [2.4.1](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.4.1)
