### ISSUE TITLE
Feature Request: move radar seek bar to top

### ISSUE THREAD

**Issue by shortwavesurfer2009** [TylerWilliamson/QuickWeather#70]
I use magnification gestures which requires a two finger swipe up from the navbar. However, this often moves the radar seek bar in the bottom right corner

**Comment by TylerWilliamson** [comment]
Thank you for bringing this to my attention. I will look into a solution when I resume work on QuickWeather later this year

**Comment by TylerWilliamson** [comment]
I had an alternative idea to address this issue. What if, instead of moving the seek bar, I instead hide all controls when the radar is single-tapped. This should both make it easier to use with magnification and easier to see the radar. What do you think?

**Comment by shortwavesurfer2009** [comment]
That is a good idea as magnification is a two finger swipe up so the controls shouldnt activate on accident

**Comment by TylerWilliamson** [comment]
I have implemented the single tap to hide the radar controls in version [2.3.6](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.3.6). I will close this ticket for now, but please let me know if you have any issues with this or if it is still difficult to use the screen magnification.
