### ISSUE TITLE
share map with forecast as a gif

### ISSUE THREAD

**Issue by avn3r90** [TylerWilliamson/QuickWeather#76]
Do you think it is possible to add the function of sharing the map that you see along with the forecast as a gif?

**Comment by avn3r90** [comment]
Or MP4 ;)

**Comment by TylerWilliamson** [comment]
This request is unfortunately outside the scope of QuickWeather. I'm also not sure how I would include it if I tried. I would instead recommend finding a suitable screen-recorder app (many of which are built into Android Operating Systems) and/or video-editor app to crop the video and cut it to the portion that you want to share.

**Comment by avn3r90** [comment]
Thank you for quick response. I was thinking about same feature like on RainViewer or Rain Alarm.
