### ISSUE TITLE
Persistent notification stopped updating 

### ISSUE THREAD

**Issue by firecat53** [TylerWilliamson/QuickWeather#78]
After the most recent app update, the persistent notification has s stopped updating until the app is opened. I have three locations manually set. The battery optimization is off and location services have permissions all the time .

Version 2.3.4 from F-Droid. No other recent Android updates that I'm aware of. Stock Pixel 6 on Android 13.

Thanks!

**Comment by TylerWilliamson** [comment]
This is a duplicate of #73. I am working on a solution
