### ISSUE TITLE
24 hour clock

### ISSUE THREAD

**Issue by Donkey-Doug** [TylerWilliamson/QuickWeather#8]
The timestamps below the graph are 12h clock only.

**Comment by TylerWilliamson** [comment]
I believe I am able to reproduce this issue. I will look into it

**Comment by TylerWilliamson** [comment]
Could you please check your language settings on your device? I manually set my device to use "English (Netherlands)" and it showed the time in 24 hour notation. I will be pushing a change later to address if you are overriding the default time format via the "Date and time" settings

**Comment by Donkey-Doug** [comment]
It could be a thing related to lineage os. I can manually select 24h clock and the clock in the status bar changes, but not in quickweather.

**Comment by TylerWilliamson** [comment]
I have resolved this issue in [1.3.3](https://github.com/TylerWilliamson/QuickWeather/releases/tag/1.3.3). You should see the same time format in QuickWeather as the rest of your device
