### ISSUE TITLE
Handle long text better

### ISSUE THREAD

**Issue by Discostu36** [TylerWilliamson/QuickWeather#81]
The app doesn't show the full text in several places. I don't know if the German strings are longer than the English ones or if it is has to do with standard font size of the device, but the app should handle this in a better way.

![Screenshot_20230727-152816](https://github.com/TylerWilliamson/QuickWeather/assets/30999326/ac3239c2-1bec-47e9-ad06-9710ffc6bcb8)

Android 12
Fairphone 4

**Comment by Discostu36** [comment]
It seems it has to do with Android font size settings. Above screenshot is not with standard but big font size.

**Comment by TylerWilliamson** [comment]
The German strings are typically longer than English ones and there is not much I can do about that. Same for large fonts and/or small screens. It's very difficult to both accomodate those situations and show all the text on the screen. Do you have suggestions for how it could be improved?

**Comment by Discostu36** [comment]
I think it's good from an accessibility perspective that you respect device font settings while other apps seem to simply use hard coded font sizes.

For the hourly view you could try different approaches:

* Scroll text that is too wide automatically from left to right and back (maybe too distracting)
* Make text area manually scrollable by user (touch and drag)
* Break text into two lines (make container higher in that case, vertically center elements)

The current conditions container could get another line if text doesn't fit. Alternatively, only show third line when user extends the element.

**Comment by nangiloc** [comment]
Hi, I’m the guy who translated the app in French. I have the same problem with French strings, especially with "Today" being translated to "Aujourd’hui". Only "Aujour" appears, and the top of the following letters. I can’t think of a shorter word.

![Screenshot_20230727-224715_QuickWeather](https://github.com/TylerWilliamson/QuickWeather/assets/136792548/1f3a08e8-a131-419f-96fc-74301f444637)

**Comment by TylerWilliamson** [comment]
First off, thank you for translating the app to French! I appreciate the work, and the French users will appreciate it too.

I just pushed a new version a few minutes ago, but I'll hopefully be pushing a fix next week to resolve the issue with the longer words by making sections scrollable

**Comment by TylerWilliamson** [comment]
Fixed in [2.4.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.4.0)

**Comment by TylerWilliamson** [comment]
I made the detail cards scrollable in 2.4.0, but have not yet resolved the issue in the main card. In the next update, it will be multi-line. Until then, I am reopening this ticket

**Comment by TylerWilliamson** [comment]
Actually fixed in [2.4.1](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.4.1)
