### ISSUE TITLE
Hourly weather?

### ISSUE THREAD

**Issue by Discostu36** [TylerWilliamson/QuickWeather#83]
There should be hourly weather available for 48 hours (it is in the graph) but the detailed view for today and tomorrow shows weather info in three hour steps.

![Screenshot_20230730-200307.png](https://github.com/TylerWilliamson/QuickWeather/assets/30999326/822777f5-b05a-4c51-88fe-2d89c9c74e85)

**Comment by TylerWilliamson** [comment]
Yes, that is a deliberate design choice. The hourly data is only available in the graph.
