### ISSUE TITLE
allow different api keys

### ISSUE THREAD

**Issue by shaul-pollak** [TylerWilliamson/QuickWeather#87]
Thanks for developing and maintaining this app!

I have a student account at openweathermap, which gives me access to the developer plan.
would it be possible to allow the use of different, higher tier services from openweathermap, and not just the OneCall type?
Currently, the app gives an error saying i need the onecall api key

**Comment by TylerWilliamson** [comment]
I am currently working on a solution to this which would use the other, free, OpenWeatherMap APIs instead of OneCall and also support the weather provider Open Meteo. Please note that weather alerts would not be available. See discussion in #75

**Comment by TylerWilliamson** [comment]
As for the other, higher tier data (additional days and hours of data), that is currently not planned, but may be added in the future. If I do, I will update this thread
