### ISSUE TITLE
Band connected to `GadgetBridge` always shows sunny icon (Open-Meteo weather provider)

### ISSUE THREAD

**Issue by baack** [TylerWilliamson/QuickWeather#89]
**Version**: 2.5.0 (pre-release).

**Problem (short)**: The band connected to `GadgetBridge` always shows "sunny" icon, no clouds nor rain. The weather provider is `Open-Meteo` without any keys.

**Details**:
The band connected to `GadgetBridge` shows correct temperature, but the graphical icon is always "Sunny" or something like that: no clouds, only the sun. The weather provider is `Open-Meteo` without any keys.
Maybe there is some problem with a piece of code in the QuickWeather with the interoperability with GadgetBridge regarding Sunny/Cloudy/Raining.

It is hard for me to understand what is happening, because GadgetBridge has no button to fetch and show temperature/weather from the weather provider (QuickWeather in my case). So I cannot tell on which step the information is getting always "Sunny".

**Comment by TylerWilliamson** [comment]
In short, this is because I needed to map the Open-Meteo weather code to the OpenWeatherMap weather code, which Gadgetbridge uses. That code is finished and will be included in the next minor release

**Comment by TylerWilliamson** [comment]
Fixed in [2.5.2](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.5.2)

**Comment by baack** [comment]
I confirm, it works properly now, the icon changes.
