### ISSUE TITLE
Error Obtaining Weather

### ISSUE THREAD

**Issue by odlg** [TylerWilliamson/QuickWeather#95]
I usually turn of mobile data and wifi during night. Every morning it has a notification saying "Error Obtaining Weather" with details "HTTP: I/O Error: Unable to resolve host api.openweathermap.org No a..."
Is it possible to detect if network is disabled/not available or similar?

**Comment by TylerWilliamson** [comment]
That error message is telling you that the internet is not available and I will likely not be changing it.

If you would rather not have that error message occur, you can either:

1. Disable the "Weather Errors" notification category
2. Disable "Weather Alerts", "Current Weather", and "Gadgetbridge" features in QuickWeather settings each night that you turn off data
